name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test de Ejercicios de POO
      id: test-de-ejercicios-de-poo
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test de Ejercicios de POO
        setup-command: sudo -H pip3 install pytest
        command: pytest
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-DE-EJERCICIOS-DE-POO_RESULTS: "${{steps.test-de-ejercicios-de-poo.outputs.result}}"
      with:
        runners: test-de-ejercicios-de-poo
